cartographer_config:
  description: |
    Understand how to configure Cartographer for different robots.
    Cartographer can be used with many robots and sensors. To get the best map result, you need to configure it correctly. All configurations can be set in the Lua configuration file.

  topics:
    laser_topic: /scan # for laser data
    odometry_topic: /odom # for odometry data
    imu_topic: /imu # for IMU data
    note: |
      IMPORTANT: You cannot configure these topic values for Cartographer, so if your robot does not publish on these topics, a remapping is necessary (check the ROS2 Basics course to learn how to do it).

  ros_integration:
    map_frame: map # The ROS frame ID for publishing sub-maps, usually 'map'.
    tracking_frame: base_footprint # Frame tracked by the SLAM algorithm. Common choices: base_link or base_footprint.
    published_frame: odom # Frame for publishing poses. Common choice if odometry is provided. Set to "base_link" otherwise.
    odom_frame: odom # Used only if provide_odom_frame is true.
    provide_odom_frame: true # Publishes the non-loop-closed local SLAM result as odom_frame.
    use_odometry: true # Enables odometry subscription on /odom.
    use_nav_sat: false # Enables GPS subscription on the 'fix' topic (requires nav_msgs/NavSatFix messages).

  laser_parameters:
    num_laser_scans: 1 # Number of laser scan topics (e.g., /scan, /scan_1, etc.).
    num_multi_echo_laser_scans: 0 # Number of multi-echo laser scan topics (e.g., /echoes, /echoes_1, etc.).
    num_subdivisions_per_laser_scan: 1 # Number of point clouds to split each laser scan.
    num_point_clouds: 0 # Number of point cloud topics (e.g., /points2, /points2_1, etc.).

  filter_parameters:
    lookup_transform_timeout_sec: 0.2 # Timeout for looking up transforms.
    submap_publish_period_sec: 0.3 # Interval to publish submap poses.
    pose_publish_period_sec: 0.005 # Interval to publish poses (200 Hz).
    trajectory_publish_period_sec: 0.03 # Interval to publish trajectory markers.
    odometry_sampling_ratio: 1.0 # Sampling ratio for odometry messages.
    fixed_frame_sampling_ratio: 1.0 # Sampling ratio for fixed frame messages.
    imu_sampling_ratio: 1.0 # Sampling ratio for IMU messages.
    landmarks_sampling_ratio: 1.0 # Sampling ratio for landmark messages.

  trajectory_builder_2d:
    min_range: 0.1 # Minimum distance to consider for map building.
    max_range: 15.0 # Maximum distance to consider for map building.
    missing_data_ray_length: 5.0 # Distance to consider as a lost laser ray.
    use_imu_data: true # Whether or not to use IMU data.
